version: '3.8'

services:
  # 백엔드 서버
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: npm run dev
    working_dir: /app/server

  # 프론트엔드 클라이언트
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/client/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SERVER_URL=http://localhost:3001
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0
    working_dir: /app/client
    depends_on:
      - server

networks:
  default:
    driver: bridge 